name: Binary (via GatoBot)

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install rust toolchain
      uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          target: x86_64-unknown-linux-gnu
          override: true
          components: rustfmt, clippy
    - name: Add nightly-x86_64
      run: rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu
    - name: Install deps
      run: ./configure.sh
    #- name: Build
    #  run: cargo build --verbose --release
    - name: Compress Diskimg
      run: ./compress-diskimg.sh
    - name: Generate SHA256 sum
      run: sha256sum target/x86_64-arch/debug/bootimage-popcorn.bin.zst > sha256sum.txt
    - name: Send to Discord
      run: |
        curl \
          -F "payload_json={\"content\": \"New build of popcorn! Timestamp: <t:$(date +%s)>\"}" \
          -F "file1=@sha256sum.txt" \
          -F "file2=@target/x86_64-arch/debug/bootimage-popcorn.bin.zst" \
          ${{ secrets.WEBHOOK_URL }}
